# Generated by Django 2.0.3 on 2018-03-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unique_tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_string', models.IntegerField(default=0, verbose_name='String from file')),
                ('given', models.CharField(max_length=81, unique=True, verbose_name='Given puzzle')),
                ('finger_print', models.CharField(max_length=189, unique=True, verbose_name='Finger print')),
                ('solved', models.CharField(blank=True, max_length=81, verbose_name='Solved puzzle')),
                ('has_solution', models.BooleanField(default=False, verbose_name='The puzzle has a solution')),
                ('single_solution', models.BooleanField(default=False, verbose_name='The puzzle has a single solution')),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='E', max_length=1, verbose_name='Level of difficulty')),
                ('time_of_solving', models.IntegerField(default=0, verbose_name='Solving time (millisecond)')),
            ],
        ),
    ]
